#!/usr/local/bin/expect -f

log_user 0
match_max 10000

set timeout 1
set send_slow {1 .01}

spawn kubectl attach -it statefulset/mindustry

expect -ex "If you don't see a command prompt, try pressing enter.\r"
sleep .1

puts "Running \"$argv\" on statefulset/mindustry..."

send -s -- "$argv\r"

expect {
	timeout { exit 1 }
	-ex "$argv\r" { exp_continue }
	-ex "\[91m\[1m\[E\]" { exit 1 }
	-ex "\[92m\[1m\[I\]"
}

exit
