apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/name: mindustry
  app.kubernetes.io/part-of: mindustry
