apiVersion: v1
kind: Service
metadata:
  name: mindustry
spec:
  type: NodePort
  ports:
    - name: tcp
      protocol: TCP
      port: 6567
      targetPort: 6567
    - name: udp
      protocol: UDP
      port: 6567
      targetPort: 6567
  selector:
    app.kubernetes.io/name: mindustry
    app.kubernetes.io/part-of: mindustry