apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mindustry
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mindustry
      app.kubernetes.io/part-of: mindustry
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mindustry
        app.kubernetes.io/part-of: mindustry
    spec:
      containers:
        - name: mindustry
          image: docker.pkg.github.com/sjparkinson/mindustry/mindustry:latest
          ports:
            - name: tcp
              containerPort: 6567
              protocol: TCP
            - name: udp
              containerPort: 6567
              protocol: UDP
      imagePullSecrets:
        - name: github
